server:
  port: 8090

spring:
  application:
    name: springboot-music-plus
  datasource:
    name: test
    url: jdbc:mysql://121.41.55.156:3306/game?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml

